version: 2
jobs:
  build:
    working_directory: ~/winsleague/winsleague
    parallelism: 3
    shell: /bin/bash --login
    # CircleCI 2.0 does not support environment variables that refer to each other the same way as 1.0 did.
    # If any of these refer to each other, rewrite them so that they don't or see https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables .
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    #  PATH: ${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin
    
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
      - checkout
      # Prepare for artifact and test results  collection equivalent to how it was done on 1.0.
      # In many cases you can simplify this from what is generated here.
      # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          working_directory: ~/winsleague/winsleague
          command: nvm install 8.9.3 && nvm alias default 8.9.3
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
      - run: yarn global add https://github.com/jasonLaster/greenkeeper-lockfile.git
      - run: ./.testing/upgrade_chrome_version.sh
      - run: ./.testing/cache_meteor.sh
      - run: ./.testing/print_environment.sh
      - run: greenkeeper-lockfile-update
      - run: ./.testing/cache_npm_dependencies.sh
      - run:
          command: ./.testing/cache_build_and_dependencies.sh
          no_output_timeout: 1200s
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.npm
            - ~/.meteor
            - ~/.cache/yarn
            - node_modules
            - .meteor/local/build
            - .meteor/local/bundler-cache
            - .meteor/local/isopacks
            - .meteor/local/plugin-cache
            - /opt/circleci/nodejs/v8.9.3/bin
            - /opt/circleci/nodejs/v8.9.3/lib/node_modules
            - ./node_modules

  acceptance_test_1:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
      - run: meteor npm run test
      - run:
          name: greenkeeper-lockfile-upload
          command: greenkeeper-lockfile-upload

  acceptance_test_2:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
      - run: meteor npm run test-app

  acceptance_test_3:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
      - run: ./tests/acceptance_run

  deploy:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
      - run: (cd .deploy/production; gpg --no-use-agent --quiet --passphrase $MUP_PASSPHRASE -o mup.js -d mup.js.gpg)
      - run: yarn global add ssh2@0.4.15 # needed for meteor-up
      - run: yarn global add mup@1.0.1 # install meteor-up for deployment
      - run: (cd .deploy/production; mup deploy)
      - run: curl https://api.rollbar.com/api/1/deploy/ -F access_token=$ROLLBAR_SERVER_ACCESS_TOKEN -F environment=production -F revision=$CIRCLE_SHA1 -F local_username=$CIRCLE_USERNAME
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: .meteor/local/log
      - store_artifacts:
          path: log
      - store_artifacts:
          path: node_cache/_logs
      - store_artifacts:
          path: ~/.config/yarn/global/yarn-error.log

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - acceptance_test_1:
          requires:
            - build
      - acceptance_test_2:
          requires:
            - build
      - acceptance_test_3:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3